export const productData = [
  {
    id: 1,
    productName: "Aditivo De Combustível Diesel S10 Bardahl Max S10",
    productDesc: "Este aditivo de combustível é produzido pela Bardahl, uma marca conhecida e respeitada na indústria automotiva. Com o número de peça 436846, você pode ter certeza de que está recebendo um produto genuíno e de alta qualidade. O volume da unidade é de 0.5 L, proporcionando uma quantidade suficiente para múltiplas aplicações.",
    price: 39.89,
    photoName: "productsImg/product01.jpg",
    soldOut: false,
  },
  {
    id: 2,
    productName: "Macaco Joelho 600kg Universal Bosal Corsa Celta Onix Prisma",
    productDesc: "O Macaco Joelho Maxi Light Universal - Mecanico é um produto de alta qualidade da marca BOSAL, conhecida por sua excelência em equipamentos automotivos.",
    price: 129.68,
    photoName: "productsImg/product02.jpg",
    soldOut: false,
  },
  {
    id: 3,
    productName: "Multimetro Com Capacímetro Digital - Mede Capacitor",
    productDesc: "Multímetro Digital Capacímetro Beep Tela Lcd Dt 9205a 9kf possui tensão máxima CC de 1000V, garantindo medições precisas e seguras.",
    price: 99.98,
    photoName: "productsImg/product03.jpg",
    soldOut: false,
  },
  {
    id: 4,
    productName: "Chave De Roda Cruz 17x19x21x23 Eda",
    productDesc: "Chave de Roda Cruz 9RU fabricada em aço resistente para maior durabilidade.",
    price: 61.50,
    photoName: "productsImg/product04.jpg",
    soldOut: false,
  },
  {
    id: 5,
    productName: "4 Litros Óleo Motor Mineral Castrol Gtx Antiborra Sae 20w50",
    productDesc: "O óleo é uma parte essencial para o bom funcionamento do motor do seu veículo, pois tem a função de limpar e lubrificar, buscando protegê-lo do desgaste e da corrosão.",
    price: 197.78,
    photoName: "productsImg/product05.jpg",
    soldOut: false,
  },
  {
    id: 6,
    productName: "Aditivo Para Radiador Pronto Uso Paraflu 1 litro Rosa",
    productDesc: "Paraflu Bio Orgânico possui a tecnologia Long Life OAT (Organic Acid Tecnology), que aumenta a vida útil do motor lubrificando a bomba d’água, a válvula termostática, evitando o ressecamento das mangueiras e protegendo contra a corrosão todos os tipos de motores.",
    price: 27.99,
    photoName: "productsImg/product06.jpg",
    soldOut: false,
  },
  {
    id: 7,
    productName: "Pneu 175/70r13 General Tire Altimax One 82t Índice de velocidade T",
    productDesc: "Baixo ruído devido à sua banda de rodagem desenvolvida com tecnologia acústica de modulação de som",
    price: 390.27,
    photoName: "productsImg/product07.jpg",
    soldOut: false,
  },
  {
    id: 8,
    productName: "3 Cera Limpadora E Polidora Orbi-max Proteção E Brilho 200g",
    productDesc: "A cera automotiva Orbi-Max remove a tinta oxidada, manchas e auxilia na remoção de sujidades diversas (piche, insetos) após sua aplicação, deixa uma camada de proteção contra as intempéries",
    price: 53.55,
    photoName: "productsImg/product08.jpg",
    soldOut: false,
  },
  {
    id: 9,
    productName: "Kit 02 Cinemático Rodoar Calibrador Roda Pneu Voar Caminhão",
    productDesc: " Este produto de alta qualidade da marca Voar é essencial para manter a calibragem correta dos pneus, garantindo uma melhor performance nas estradas.",
    price: 102.99,
    photoName: "productsImg/product09.jpg",
    soldOut: false,
  },
  {
    id: 10,
    productName: "Kit 4 Água Para Bateria E Radiador Desmineralizada Paraflu",
    productDesc: "A Água Desmineralizada PARAFLU é recomendada para uso em sistemas de arrefecimento de motores endotérmicos e também em sistemas elétricos automotivos.",
    price: 49.26,
    photoName: "productsImg/product10.jpg",
    soldOut: false,
  },
  
];
